correct description for key task parameter
puppetlabs/puppetlabs-http_request pull request #8
Opened 2021-03-04 07:06 UTC by golflimaechoecho

update parameter description to reflect key should be contents not absolute path to file

The key parameter is passed to [`OpenSSL::PKey::RSA.new()`](https://ruby-doc.org/stdlib-2.6.1/libdoc/openssl/rdoc/OpenSSL/PKey/RSA.html#method-c-new) which "Generates or loads an RSA keypair. If an integer key_size is given it represents the desired key size. Keys less than 1024 bits should be considered insecure. A key can instead be loaded from an encoded_key which must be PEM or DER encoded. [...]".

2021-03-04 07:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-http_request?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-http_request?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-http_request?pullRequest=8) it.</sub>

2021-03-04 22:23 UTC, beechtom commented
@golflimaechoecho Thanks for catching this! I think we're going to consider this a bug in the code as opposed to an error in documentation - since the intent was to read the key from a file - and update the task itself. Let me know if you'd prefer us to make those changes instead and we can put it on our list.

2021-03-04 22:36 UTC, golflimaechoecho commented
@beechtom Thanks for the background - agree that updating the task to read from a file is the better approach; if that is straightforward to change then happy to do that instead. The documentation update was more an interim step in case there were other things in flight that would prevent the task from being updated in the short term.

2021-03-04 22:46 UTC, beechtom commented
@golflimaechoecho Very straightforward. I think you already located the line in the task that causes the issue: https://github.com/puppetlabs/puppetlabs-http_request/blob/main/tasks/init.rb#L66

That just needs to be updated to:
```ruby
client.key         = OpenSSL::PKey::RSA.new(File.read(opts[:key])) if opts[:key]
```

And no blockers on our end. As soon as we get the change merged in we can release a new version of the module.

2021-03-04 23:11 UTC, golflimaechoecho commented
@beechtom Thank you :) reverted the documentation changes and pushed the update to the task now

2021-03-04 23:27 UTC, beechtom requested changes
@golflimaechoecho Looks good, and works as expected! Reads in the contents of a key file and fails with a helpful error if the file does not exist. Thanks for picking up the change.

One last thing before we get this merged in: can you squash your commits so there's just 1?

2021-03-04 23:58 UTC, golflimaechoecho commented
@beechtom done :)

2021-03-05 00:00 UTC, beechtom approved these changes

2021-03-05 00:00 UTC, merged